### PR TITLE
disable update button for package

### PR DESCRIPTION
**Pull request by selvaprakash92**
#### Type of change

- Bug fix

### CODE REVIEW

**Review by dshuffma-ibm — CHANGES_REQUESTED** [review]
use the [actionsHelper.js](https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/apollo/src/utils/actionsHelper.js) instead of manually looking at the role, this one could use the `canManageComponent` function

**Review by dshuffma-ibm — CHANGES_REQUESTED** [review]
this modal does not have a `userInfo` defined, nor does it have `feature_flags`, so this errors out

**Comment by selvaprakash92** [comment]
> this modal does not have a `userInfo` property, nor does it have `feature_flags`, so this errors out

@dshuffma-ibm updated the logic that fixed the errors, Thanks

**Review by dshuffma-ibm — CHANGES_REQUESTED** [review]
close! but these fields are not registered in the modal, so they will not be accessible. actually instead of passing them in, just pull them like we do on other modals, use the `connect` method
 like: https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/apollo/src/components/CADetails/CADetails.js#L782

**Review by dshuffma-ibm — APPROVED** [review]
+1 thanks

**Pull request merged**
