### PR TITLE
Changes as per 2.5.3 images

### PR DESCRIPTION
**Pull request by ketulsha**
Signed-off-by: Ketul Shah shah.ketul@ibm.com

#### Type of change

- Test update

#### Description

1. Added one explicit wait in 8-InstallInstantiate1xSmartContract.feature
2. Updated "2.2" to "2.4.3" to be selected from Fabric dropdown as per 2.5.3 images

### CODE REVIEW

**Review by dshuffma-ibm — CHANGES_REQUESTED** [review]
this looks fine, however can you get the signature on your commit? 

you should be able to run `git commit -s --amend` on this branch, and then a force push to append your signature line.

**Comment by dshuffma-ibm** [comment]
@ketulsha ^^

**Comment by ketulsha** [comment]
> @ketulsha ^^

Thanks @dshuffma-ibm. I have force pushed the commit. Please review.

**Comment by ketulsha** [comment]
> this looks fine, however can you get the signature on your commit?
> 
> you should be able to run `git commit -s --amend` on this branch, and then a force push to append your signature line.

Thanks @dshuffma-ibm. I have force pushed the commit. Please review.

**Review by dshuffma-ibm — APPROVED** [review]

**Comment by dshuffma-ibm** [comment]
thanks!

**Pull request merged**
