### PR TITLE
log added on application startup tasks

### PR DESCRIPTION
**Pull request by ckpaliwal**
#### Type of change

- Improvement (Performance improvement etc)

#### Description

- Performance improvement update and log added

### CODE REVIEW

**Review by dshuffma-ibm — APPROVED** [review]
+

**Review by dshuffma-ibm — CHANGES_REQUESTED** [review]
strangely a test is failing

**Comment by ckpaliwal** [comment]
Resolved

**Review by dshuffma-ibm — APPROVED** [review]
+1

**Pull request merged**
